config/routes.rb
Rails.application.routes.draw do
  root 'short_url#index'
  #short_url
  post 'short_url/create_short_url' => 'short_url#create_short_url'
  post 'short_url/search_for_long_url' => 'short_url#search_for_long_url'
  
  #admin
  get 'admin' => 'admin#index'

  #customer
  get   'customer' => 'customer#index'
  post 'customer/create_short_url' => 'customer#create_short_url'

  #short url api
  post 'short_url/api/create_short_url' => 'short_url_api#create_short_url'
  post 'short_url/api/search_long_url' => 'short_url_api#search_long_url'

  #access to long url
  get "/:keyword" => "short_url#access_to_long_url", constrains: {:keyword => /(0-9a-zA-Z){3,}/}
end

app/models/short_url.rb
require "utils/short_url_util"
class ShortUrl < ActiveRecord::Base
	self.table_name = "short_url"
	SYSTEM_GENERATE = 0
	CUSTOMER_GENERATE = 1

	def self.insert_data(params)
		short_url = self.new
		short_url.url = params[:long_url_input]
		short_url.keyword = params[:keyword] if !params[:keyword].blank?
		short_url.create_type = !params[:customer_generate] ? SYSTEM_GENERATE : CUSTOMER_GENERATE
		short_url.addtime = Time.now.to_i
		short_url.save!
		short_url
	end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	ITEMS_PER_PAGE = 10
	def index
		@short_urls = ShortUrl.where("status = ?", true).paginate(:page => params[:page], :per_page => ITEMS_PER_PAGE)
		respond_to {|format| format.html}
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # reload log
  class ActiveSupport::Logger::SimpleFormatter
    def call(severity, time, name, msg)
      sprintf("%s %s %s [%s] %s - %s\n", time.strftime("%Y-%m-%d %H:%M:%S"), `hostname`.to_s.gsub("\n", ""), "Hulk", severity, Process.pid, msg)
    end
  end

  def get_logger(log_name)
    ActiveSupport::TaggedLogging.new(Logger.new("./log/" + log_name))
  end
end

app/controllers/customer_controller.rb
class CustomerController < ApplicationController
	def index
	end

	def create_short_url
		logger = get_logger("Customer.log")
		@not_error = true
		@short_url = ShortUrl.where("keyword = ?", params[:keyword]).first
		respond_to {|format| format.js} and return if !@short_url.nil?
		if ShortUrlUtil.check_url_validation(params[:long_url_input]) == ShortUrlUtil::REGEX_MATCHED
			begin
				params[:customer_generate] = true
				@short_url = ShortUrl.insert_data(params)
			rescue => e
				logger.tagged("short url") {logger.error("error: #{$!}. at: #{$@}")}
				@not_error = false
			end
		end
		respond_to {|format| format.js}
	end
end

app/controllers/short_url_api_controller.rb
require "utils/short_url_util"
class ShortUrlApiController < ApplicationController
	skip_before_filter :verify_authenticity_token
	def create_short_url
		#参数非空检测
		required_params = [:long_url_input, :customer_generate]
		required_params.each do |item|
			render :json => mapping_render_format(false, "参数#{item}未传入值", {}) and return if params[item].nil?
		end
		logger = get_logger("short_url_api.log")
		if ShortUrlUtil.check_url_validation(params[:long_url_input]) == ShortUrlUtil::REGEX_MATCHED
			begin
				short_url = ShortUrl.insert_data(params)
				if params[:keyword].blank?
					short_url.keyword = ShortUrlUtil.base62(short_url.id)
					short_url.save!
				end
				render :json => mapping_render_format(true, "成功", {"short_url" => Rails.configuration.base_short_url + short_url.keyword})
			rescue => e
				logger.tagged("short url") {logger.error("error: #{$!}. at: #{$@}")}
				render :json => mapping_render_format(false, "系统内部错误,请联系管理员查看原因", {})
			end
		else
			render :json => mapping_render_format(false, "输入的url不合法,请重新输入", {})
		end
	end

	def search_long_url
		#参数非空检测
		required_params = [:short_url_input]
		required_params.each do |item|
			render :json => mapping_render_format(false, "参数#{item}未传入值", {}) and return if params[item].blank?
		end

		if ShortUrlUtil.check_url_validation(params[:short_url_input]) == ShortUrlUtil::REGEX_MATCHED
			keyword = ShortUrlUtil.process_url(params[:short_url_input])
			if !keyword.blank?
				long_url = get_long_url(keyword)
				if !long_url.blank?
					render :json => mapping_render_format(true, "成功", {"long_url" => long_url})
				else
					render :json => mapping_render_format(false, "输入的url没有命中任何数据,请重新输入", {})
				end
			else
				render :json => mapping_render_format(false, "输入的url中没有短链关键词,请重新输入", {})
			end
		else
			render :json => mapping_render_format(false, "输入的url不合法,请重新输入", {})
		end
	end

	private

	def get_long_url(keyword)
		short_url = ShortUrl.where("keyword = ?", keyword).first
		short_url.nil? ? "" : short_url.url
	end

	def mapping_render_format(success, msg, data)
		 {"success" => success, "message" => msg, "data" => data}
	end
end

app/controllers/short_url_controller.rb
require "utils/short_url_util"
class ShortUrlController < ApplicationController
	def index
	end

	def search_for_long_url
		@short_url = nil
		@not_error = true
		if ShortUrlUtil.check_url_validation(params[:short_url_input]) == ShortUrlUtil::REGEX_MATCHED
			keyword = ShortUrlUtil.process_url(params[:short_url_input])
			@short_url = ShortUrl.where("keyword = ?", keyword).first if !keyword.nil?
		end
		respond_to {|format| format.js}
	end

	def create_short_url
		logger = get_logger("short_url.log")
		@not_error = true
		@short_url = nil
		if ShortUrlUtil.check_url_validation(params[:long_url_input]) == ShortUrlUtil::REGEX_MATCHED
			begin
				params[:customer_generate] = false
				@short_url = ShortUrl.insert_data(params)
				@short_url.keyword = ShortUrlUtil.base62(@short_url.id)
				@short_url.save!
			rescue => e
				logger.tagged("short url") {logger.error("error: #{$!}. at: #{$@}")}
				@not_error = false
			end
		end
		respond_to {|format| format.js}
	end

	def access_to_long_url
		short_url = request.env["REQUEST_URI"]
		keyword = ShortUrlUtil.process_url(short_url)
		short_url = ShortUrl.where("keyword = ?", keyword).first
		if short_url.nil?
			redirect_to "/404.html"
		else
			short_url.use_count += 1
			short_url.save
			redirect_to short_url.url, :status => 301
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/index.html.erb
<div class="panel-body">
	<table id="short_url_table" class="table table-bordered">
		<thead>
			<th style="width:10%">ID</th>
			<th style="width:50%">Url</th>
			<th style="width:10%">短链关键字</th>
			<th style="width:10%">访问次数</th>
			<th style="width:20%">创建时间</th>
		</thead>
		<tbody>
			<% @short_urls.each do |item| %>
				<tr>
					<td><%= item.id %></td>
					<td><%= item.url %></td>
					<td><%= item.keyword %></td>
					<td><%= item.use_count %></td>
					<td><%= Time.at(item.addtime).strftime("%Y-%m-%d %H:%M:%S") %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<% if !@short_urls.blank? %>
	<%= will_paginate @short_urls, renderer: BootstrapPagination::Rails %>
<% end %>

app/views/customer/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="alert-modal" aria-labelledby="alert-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">提示</h4>
      </div>
      <div class="modal-body" id="alert-modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">知道了</button>
      </div>
    </div>
  </div>
</div>
<script>
	function myAlert(msg) {
		$("#alert-modal-body").html(msg);
		$("#alert-modal").modal({keyboard: true});
	};
</script>

app/views/customer/_show_url.html.erb
<%= render :partial => "modal" %>
<% if (!@short_url.nil? && @not_error) %>
	<div class="show_url_detail">
		<div class="row">
			<label class="control-label col-md-2">短网址: </label>
			<div class="control-label col-md-2">
				<a href=<%=Rails.configuration.base_short_url+ @short_url.keyword%>><%=Rails.configuration.base_short_url+ @short_url.keyword%></a>
			</div>
		</div>
		<div class="row">
			<label class="control-label col-md-2">原网址: </label>
			<div class="control-label col-md-2">
				<a href=<%= @short_url.url %>><%= @short_url.url %></a>
			</div>	
		</div>
	</div>
<% end %>
<script>
	$(document).ready(function() {
		if(<%= @short_url.nil? %>) {
			myAlert("网址不存在或网址格式错误,请您仔细检查后重新输入!!!");
		}
		if(<%= !@not_error %>) {
			myAlert("系统内部错误,请联系管理员处理!!!");
		}
	});
</script>

app/views/customer/create_short_url.js.erb
$("#show_short_url").html("<%= escape_javascript(render :partial => "show_url")%>")

app/views/customer/index.html.erb
<div class="benefits container" style="padding-top:20px">
	<div class="container" style="padding-left: 15px;margin-left: 400px;">
		<img src="/assets/hulk.ico" style="height: 300px;	">
	</div>
	<br />
	<div class="">
		<form class="form-horizontal" id="gen_short_url" method="post" action="customer/create_short_url" data-remote="true">
			<div class="col-md-6 col-md-offset-3">
				<div id="short_url_input_div">
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon3">自定义短链:fdafd</span>
						<input class="form-control" id="keyword" name="keyword" type="text" />
					</div>
					<br/>
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon3">https://example.com</span>
						<input class="form-control" id="long_url_input" name="long_url_input" type="text" />
						<span class="input-group-btn">
							<button class="btn btn-primary" style="background-color:#478A10;border-color: #478A10;"type="submit" id="btn_submit_long">网址缩短</button>
						</span>
					</div>
					<div id="show_short_url"></div>
				</div>
			</div>
		</form>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  	<%= csrf_meta_tags %>
  	<link href="/assets/Happy Hulks.ico" rel="shortcut icon">
	<title>Hulk-短地址服务</title>
</head>
<body style="padding-top:60px;padding-bottom:40px;">
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container" style="width:95%;">
				<div>
					<a class="navbar-brand" href="/">
 						<span style="margin-top:4px;font-family:'Stardos Stencil',cursive;font-size:1.3em;color:#fff;">H</span>
						<span style="margin-left:-5px;margin-top:2px;font-family:'Stardos Stencil',cursive;font-size:1.3em;">ulk</span>
					</a>
				</div>
				<ul class="nav" style="font-size:16px;padding-top:5px">
					<li style="float:left" class="<%= 'active_nav' %>">
						<a id="tools_drop" href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" role="button" aria-expanded="false" style="color:#478A10;">管理平台<span class="caret"></span>
						</a >
						<ul class="dropdown-menu" style="" role="menu" aria-labelledby="tools_drop">
							<li class="nav_dropdown_li active_nav">
								<a style="padding-top:9px;color:#478A10;" class="nav_dropdown_a" href="/admin"><span class="nav_span">管理平台</span></a>
							</li>
							<li class="nav_dropdown_li active_nav">
								<a style="padding-top:9px;color:#478A10;" class="nav_dropdown_a" href="/customer"><span class="nav_span">自定义短链</span></a>
							</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container" style="width:95%">
		<%= yield %>
	</div>
</body>
</html>

app/views/short_url/_modal.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="alert-modal" aria-labelledby="alert-modal-label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">提示</h4>
      </div>
      <div class="modal-body" id="alert-modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">知道了</button>
      </div>
    </div>
  </div>
</div>
<script>
	function myAlert(msg) {
		$("#alert-modal-body").html(msg);
		$("#alert-modal").modal({keyboard: true});
	};
</script>

app/views/short_url/_show_url.html.erb
<%= render :partial => "modal" %>
<% if (!@short_url.nil? && @not_error) %>
	<div class="show_url_detail">
		<div class="row">
			<label class="control-label col-md-2">短网址: </label>
			<div class="control-label col-md-2">
				<a href=<%=Rails.configuration.base_short_url+ @short_url.keyword%>><%=Rails.configuration.base_short_url+ @short_url.keyword%></a>
			</div>
		</div>
		<div class="row">
			<label class="control-label col-md-2">原网址: </label>
			<div class="control-label col-md-2">
				<a href=<%= @short_url.url %>><%= @short_url.url %></a>
			</div>	
		</div>
	</div>
<% end %>
<script>
	$(document).ready(function() {
		if(<%= @short_url.nil? %>) {
			myAlert("网址不存在或网址格式错误,请您仔细检查后重新输入!!!");
		}
		if(<%= !@not_error %>) {
			myAlert("系统内部错误,请联系管理员处理!!!");
		}
	});
</script>

app/views/short_url/create_short_url.js.erb
$("#show_short_url").html("<%= escape_javascript(render :partial => "show_url")%>")

app/views/short_url/index.html.erb
<div class="benefits container" style="padding-top:20px">
	<div class="container" style="padding-left: 15px;margin-left: 400px;">
		<img src="/assets/Happy Hulks.ico" style="height: 300px;	">
	</div>
	<br />
	<div class="">
		<form class="form-horizontal" id="gen_short_url" method="post" action="short_url/create_short_url" data-remote="true">
			<div class="switch" style="margin-left: 300px;">
				<input id="url_switch" name="url_switch" type="checkbox" checked />
			</div>
			<br />
			<div class="col-md-6 col-md-offset-3">
				<div id="short_url_input_div">
					<div class="input-group">
						<span class="input-group-addon" id="basic-addon3">https://example.com</span>
						<input class="form-control" id="long_url_input" name="long_url_input" type="text" />
						<span class="input-group-btn">
							<button class="btn btn-primary" style="background-color:#478A10;border-color: #478A10;"type="submit" id="btn_submit_long">网址缩短</button>
						</span>
					</div>
					<div id="show_short_url"></div>
				</div>
				<div id="long_url_input_div">
					<div class="input-group" id="transfer_long">
						<span class="input-group-addon" id="basic-addon3">http://lh.cn/er5trg</span>
						<input class="form-control" id="short_url_input" name="short_url_input" type="text" />
						<span class="input-group-btn">
							<button class="btn btn-primary" style="background-color:#478A10;border-color: #478A10;"type="submit" id="btn_submit_short">网址还原</button>
						</span>
					</div>
					<div id="show_long_url"></div>
				</div>
			</div>
		</form>
	</div>
</div>

<script>
	$(document).ready(function() {
		$("#long_url_input_div").hide();
	});
	var toShortUrl = true;
	$("#url_switch").bootstrapSwitch({
		onText: "缩短网址",
		offText: "还原网址",
		onColor: "info",
		offColor: "success",
		onSwitchChange:function(event, state) {
			toShortUrl = !toShortUrl;
			if(toShortUrl) {
				$("#long_url_input_div").hide();
				$("#short_url_input_div").show();
				$("#show_long_url").empty();
				$("#long_url_input").val("");
				$("#gen_short_url").attr("action", "short_url/create_short_url");
			} else {
				$("#long_url_input_div").show();
				$("#short_url_input_div").hide();
				$("#show_short_url").empty();
				$("#short_url_input").val("");
				$("#gen_short_url").attr("action", "short_url/search_for_long_url");
			}
		}
	});
</script>

app/views/short_url/search_for_long_url.js.erb
$("#show_long_url").html("<%= escape_javascript(render :partial => "show_url")%>")